version: "3"
services:
  client:
    image: node:8
    volumes:
      - .:/usr/src
      - /usr/src/client/node_modules/.cache
    working_dir: /usr/src/client
    command: yarn start
    networks:
      - frontend
    ports:
      - "3000:3000"
    environment:
      PUBLIC_URL: "http://localhost:3000"
      REACT_APP_API_URL: "http://localhost:8080"

  server:
    image: node:8
    volumes:
      - .:/usr/src
    working_dir: /usr/src/server
    command: yarn start
    networks:
      - frontend
      - backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      JWT_SECRET: "secret"
      DATABASE_URL: "postgresql://postgres@db:5432/postgres"
      REDIS_URL: "redis://redis:6379"

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data:
