# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

server_defaults: &server_defaults
  <<: *defaults
  working_directory: ~/repo/server

client_defaults: &client_defaults
  <<: *defaults
  working_directory: ~/repo/client

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - node-modules-{{ arch }}-{{ .Branch }}
            - node-modules
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
            - server/node_modules
            - client/node_modules
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  lint_server:
    <<: *server_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: yarn lint

  build_server:
    <<: *server_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build

  test_server:
    <<: *server_defaults
    docker:
      - image: circleci/node:8.11
        environment:
          JWT_SECRET: secret
          DATABASE_URL: postgresql://root@localhost/circle_test
          REDIS_URL: redis://localhost
      - image: circleci/postgres:9.6.5-alpine-ram
      - image: circleci/redis:5.0.1-alpine
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run E2E tests
          command: yarn test:e2e --coverage
      - run:
          name: Upload test coverage
          command: npx codecov -p ~/repo

  lint_client:
    <<: *client_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint
          command: yarn lint

  build_client:
    <<: *client_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  test_client:
    working_directory: ~/repo
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build client
          command: |
            docker build -t client --build-arg PUBLIC_URL=http://client:5000 --build-arg API_URL=http://server:5000 client

      - run:
          name: Build server
          command: |
            docker build -t server server 

      - run:
          name: Start PostgreSQL server
          command: docker run -d --name postgres --network=reviews postgres
          background: true

      - run:
          name: Start Redis server
          command: docker run -d --name redis --network=reviews redis
          background: true

      - run:
          name: Start API server
          command: docker run -d --name server --network=reviews -e SEED_MODULE=true -e DATABASE_URL=pg://postgres@postgres:5432 -e REDIS_URL=redis://redis:6379 -e JWT_SECRET=secret -e PORT=5000 -p 5000:5000 server
          background: true

      - run:
          name: Start client server
          command: docker run -d --name client --network=reviews -e REACT_APP_API_URL=pg://server:5000 -e PORT=5000 client
          background: true

      - run:
          name: Run Cypress
          command: docker run --rm -it --name cypress --network=reviews -v $PWD:/e2e -w /e2e/client -e CYPRESS_BASE_URL=http://client:5000 -e CYPRESS_API_URL=http://server:5000 cypress/included:3.2.0

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build_server:
          requires:
            - checkout_code
      - lint_server:
          requires:
            - checkout_code
      - test_server:
          requires:
            - checkout_code
      - build_client:
          requires:
            - checkout_code
      - lint_client:
          requires:
            - checkout_code
      - test_client:
          requires:
            - checkout_code
